### ISSUE TITLE
401 - unauthorized

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/Homebridge-HomeSeer4#18]
Just installed and getting 401 unauthorized.    Thought maybe it was because I'm using SSL, so tried disabling and problem persists.  

<pre>(node:12784) UnhandledPromiseRejectionWarning: *HTTP Error 401 * - Improper login and password specified in your config.json setup file. Correct and try again.</pre>

The link it shows in [HomeSeer] Get Control URL is correct.  Copied and pasted it out of the log and it works fine.  

<pre>[HomeSeer] Get Control URL is: https://Mylogin:Mypassword@192.168.1.5/JSON?request=getcontrol</pre>

**Comment by jvmahon** [comment]
As a warning, this code is still "beta" - but thanks for trying it as that helps iron out the bugs!

The plugin is now set up so that the user has to define a login and a password on a separate line of the config.json file rather than as part of the "host" line.  I did a major rewrite of the networking section of the plugin so as to fix some bugs and increase speed when controlling a large number of devices. Unfortunately, I hadn't considered what would happen if login / password was specified in the "host" line instead of separately - I'll go back and take another look and see if I can make that work as an alternative. For now, can you try breaking them out as set out below and let me know if that works.

See the sample config.json file in: https://github.com/jvmahon/Homebridge-HomeSeer4/tree/master/config   where it shows the start of the "platform" section:

		"platform": "HomeSeer",              
		"name": "HomeSeer",                 
		"host": "http://192.168.1.1:80",
		"login":"default",
		"password":"default",

**Comment by meluvalli** [comment]
I actually have it like you show above.  But in the log it's showing the full path with username/password in the URL.

It's getting the 401 error no matter what I do, so I temporarily, disabled password checking for local subnet in HomeSeer so i can test/try this plugin :)

**Comment by jvmahon** [comment]
OK, yes, please disable the password checking for local subnet. Also, after you make any change in the network settings in HomeSeer, you should shut down and then re-start HomeSeer (HomeSeer seems to require a reboot to effect a change in networking settings).

**Comment by jvmahon** [comment]
Also, I just noticed that your Control URL is missing the port number.
Did you include the :80 at the end of the host number as shown above?
I'll need to add some error checking for this.

**Comment by meluvalli** [comment]
I did not include the port.  I was actually using HTTPS, so on port 443.  I can try this and post update in a few minutes.

**Comment by meluvalli** [comment]
Ok, re-enabled password requirement through HomeSeer, added port number ":443" to config.json, shutdown HomeSeer, re-opened it, and still get 401 error.

I know my username and password is correct.  The homeseer log, doesn't show the ":443" at the end of the URL.

Log:
<pre>[12/17/2019, 11:22:44 AM] [HomeSeer] Status URL is: https://[MyUserName]:[MyPassword]@192.168.1.5/JSON?request=getstatus
[12/17/2019, 11:22:44 AM] [HomeSeer] Get Control URL is: https://[MyUserName]:[MyPassword]@192.168.1.5/JSON?request=getcontrol
[12/17/2019, 11:22:44 AM] Loading 0 accessories...
Load homebridge-HomeSeerPlatform.HomeSeer
(node:11512) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:11512) UnhandledPromiseRejectionWarning: *HTTP Error 401 * - Improper login and password specified in your config.json setup file. Correct and try again.</pre>

Config:
<pre>        {
            "platform": "HomeSeer",
            "name": "HomeSeer",
            "host": "https://192.168.1.5:443",
			"login":"[MyUserName]",
			"password":"[MyPassword]",
            "events": [
...
</pre>

**Comment by jvmahon** [comment]
Try using port 80 and http://
I did not test with https://
(But I'll put that on the list of "next things" to test)

**Comment by meluvalli** [comment]
Ok.  Tried http instead of https and still 401 error.  And you're correct, my http is on a different port than 80, and now it's showing the port in the url.

I wondered it was my username/password (Special characters), but changed my username/password temporarily to something simple (all lowercase letters only), and still have the same issue.  So this isn't the problem either.  I'm kinda at a loss.  homebridge-homeseer-plugin-2018 worked just fine with this same username and password.  I would think the only thing you changed was separating it out of the URL in the config.json file.   So why would it not work now?

**Comment by jvmahon** [comment]
Did you disable password / login checking on the local subnet? If not, can you try that.
And please shut down Homebridge and HomeSeer then restart after making any networking change.

I'm at a loss since this is working for me, but I'm sure it is solvable.

**Comment by jvmahon** [comment]
Also, can you test to make sure your username / password was properly recognized by HomeSeer.
To do that, you can manually execute the URL from any browser window using . . .

`````
http://username:password@127.0.0.1:80/JSON?request=getControl
`````

If you get a bunch of JSON code back, its working. If you are getting an error, then it isn't the plugin but, rather, its an error in the username / login.

**Comment by meluvalli** [comment]
To answer your first post, I do NOT normally have it set to bypass local subnet.  I disable password checking only for testing and to allow me to get past the 401 error. 

With password being required in HomeSeer, yes the direct URL link (with password in URL) works.  That's why I'm at a loss for the 401 :(

**Comment by jvmahon** [comment]
I think this may be due to the Javascript code not recognizing a security certificate for the HTTPS connection. The only resolution I have now is to not use https:// until I can do some more testing.

**Comment by meluvalli** [comment]
I think you meant to use http ;)...  But, I tried that and still get the 401.  So, this isn't the case :(

**Comment by jvmahon** [comment]
I found a few networking bugs - not sure if I caught the one that is causing you problems.
Try doing an update
````` 
npm -g update
`````

**Comment by meluvalli** [comment]
For this test, I decided to make sure I wasn't using SSL.  I revert back to HTTP to ENSURE no issues 
with CERTs.  

**Again, if I copy the Status URL from my local machine, the link works and loads the devices in a browser.  So UserName/Password is NOT the issue.**

No dice on this issue :(

<pre>
[12/17/2019, 11:19:00 PM] [HomeSeer] Initializing HomeSeer platform...
[12/17/2019, 11:19:00 PM] [HomeSeer] Status URL is: http://[MyLogin]:[MyPassword]@192.168.1.105:8189/JSON?request=getstatus
[12/17/2019, 11:19:00 PM] [HomeSeer] Get Control URL is: http://[MyLogin]:[MyPassword]@192.168.1.105:8189/JSON?request=getcontrol
[12/17/2019, 11:19:00 PM] Loading 0 accessories...
Load homebridge-HomeSeerPlatform.HomeSeer
(node:9112) UnhandledPromiseRejectionWarning: *HTTP Error 401 * - Improper login and password specified in your config.json setup file. Correct and try again.
(node:9112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Comment by jvmahon** [comment]
I pushed out another release which should give a bit more debugging info. so please do an update and let me know what happens.  Also, what's confusing is you seem to have this working - but with that error, nothing should work, so I'm not quite sure what is happening.

**Comment by meluvalli** [comment]
Sorry, today has been a busy day so haven’t had much time to test.  I will be able to test this in a little bit.  As far as your comment about me having it working, I disable credentials requirement for HomeSeer to make it work.  It works fine as long as I have it set to not require username/password 😀

**Comment by meluvalli** [comment]
I went ahead and created a "temporary" username/password for my system so I could post without masking ANYTHING.  Here is what we get:

<pre>
[12/18/2019, 2:21:45 PM] [HomeSeer] Status URL is: http://testuser:testpassword@10.40.162.90:8189/JSON?request=getstatus
[12/18/2019, 2:21:45 PM] [HomeSeer] Get Control URL is: http://testuser:testpassword@10.40.162.90:8189/JSON?request=getcontrol
[12/18/2019, 2:21:45 PM] Loading 0 accessories...
Load homebridge-HomeSeerPlatform.HomeSeer
[12/18/2019, 2:21:45 PM] [HomeSeer] Line 191 - Error is: StatusCodeError: 401 - undefined
[12/18/2019, 2:21:45 PM] [HomeSeer] *HTTP Error 401 - line 192 * - Improper login and password specified in your config.json setup file. Correct and try again.
(node:8536) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - undefined
    at new StatusCodeError (C:\HomeBridge\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\HomeBridge\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\HomeBridge\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\HomeBridge\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (C:\HomeBridge\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (C:\HomeBridge\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
(node:8536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/18/2019, 2:21:45 PM] [HomeSeer] Line 191 - Error is: StatusCodeError: 401 - undefined
[12/18/2019, 2:21:45 PM] [HomeSeer] *HTTP Error 401 - line 192 * - Improper login and password specified in your config.json setup file. Correct and try again.
</pre>

**Again, works in web browser, so I know the password is correct (Link copied from 1st line in log)** 

![image](https://user-images.githubusercontent.com/8729476/71120685-894a7c00-21a2-11ea-94c1-d9e0cd847bb8.png)

**Comment by meluvalli** [comment]
To show username and password are working, I verified with wget:

**With supplied credentials**
<pre>
C:\Users>wget http://testuser:testpassword@10.40.162.90:8189/JSON?request=getstatus
--2019-12-18 14:32:00--  http://testuser:*password*@10.40.162.90:8189/JSON?request=getstatus
Connecting to 10.40.162.90:8189... connected.
HTTP request sent, awaiting response... 401
Authentication selected: Basic realm="HomeSeer0"
Connecting to 10.40.162.90:8189... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101005 (99K) [application/json]
Saving to: 'JSON@request=getstatus'

JSON@request=getstatus        100%[=================================================>]  98.64K  --.-KB/s    in 0.008s

2019-12-18 14:32:01 (12.2 MB/s) - 'JSON@request=getstatus' saved [101005/101005]

</pre>

**Without credentials:**
<pre>
C:\Users>wget http://10.40.162.90:8189/JSON?request=getstatus
--2019-12-18 14:32:07--  http://10.40.162.90:8189/JSON?request=getstatus
Connecting to 10.40.162.90:8189... connected.
HTTP request sent, awaiting response... 401

Username/Password Authentication Failed.
</pre>

**Comment by meluvalli** [comment]
Oh interesting!!!  I just noticed in my above post!  It get's a 401 first, then succeeds!  Is this the problem????

**Comment by jvmahon** [comment]
Don't know why you would get a 401 and then succeed.

What version of HomeSeer are you using?  All my testing was on version 3.0.0.548. If not using that version, can you do an update?
Are you on Linux or Windows -- All my testing is on Windows
Finally, which version of Node are you using - I'm using 13.3

**Comment by jvmahon** [comment]
A fix has been posted in version 0.0.10 of the plugin so please do a npm update, try again, and let me know if it is working
`````
npm -g update
`````

P.S. - The following command will list your plugins and you can use it to confirm that the update to version 0.0.10 was successful.
`````
npm -g list --depth=0
`````

**Comment by meluvalli** [comment]
Great job!!!  Ok, but now there is another issue :(
<pre>
[12/18/2019, 10:10:40 PM] [HomeSeer] RequestError: Error: write EPROTO 14332:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:
 : Error line 198 - error getting device status info. Check if HomeSeer is running and that JSON interface is enabled, then start homebridge again. Status code: undefined
(node:8864) UnhandledPromiseRejectionWarning: RequestError: Error: write EPROTO 14332:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:

    at new RequestError (C:\HomeBridge\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\HomeBridge\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\HomeBridge\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\HomeBridge\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (C:\HomeBridge\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:407:9)
    at TLSSocket.emit (events.js:210:5)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
(node:8864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/18/2019, 10:10:40 PM] [HomeSeer] RequestError: Error: write EPROTO 14332:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:
 : Error line 228 - error getting device Control info. Check if HomeSeer is running and that JSON interface is enabled, then start homebridge again. Status code: undefined
</pre>

This happens if using SSL only.  My certificate is a trusted certificate Issued by: Let's Encrypt Authority X3.  DNS maches and certificate dates are valid.  So that's not the problem I don't believe.  

Why do I always have to give good news with bad news :(  haha!

**Comment by meluvalli** [comment]
> Don't know why you would get a 401 and then succeed.
> 
> What version of HomeSeer are you using? All my testing was on version 3.0.0.548. If not using that version, can you do an update?
> Are you on Linux or Windows -- All my testing is on Windows
> Finally, which version of Node are you using - I'm using 13.3

Running Windows Version.  My Node is 13.2.  I should upgrade this!  I try not to touch it because I usually break stuff when I do :(...  HomeSeer is 3.0.0.398

**Comment by jvmahon** [comment]
I"m not sure, but I think this may be to Node no longer supporting 'old' versions of TLS. I'll investigate a bit more. Or possibly relating to fact you're using an 'older' version of HomeSeer and as SSL support is a "labs" section feature, maybe the 3.0.0.398 version doesn't have it quite worked out?

**Comment by meluvalli** [comment]
Hmm.  Ok.  Just strange it works on homebridge-homeseer-plugin-2018 then...

**Comment by jvmahon** [comment]
Good point - that certainly suggest it is in the plugin. I just don't know, but I'll check some more over the weekend to see if I can get this fixed.

**Comment by meluvalli** [comment]
Thank you.  I REALLY do appreciate all your help!

**Comment by jvmahon** [comment]
Can you do a test for me?
The file index.js 

line 169 reads: 		
var getStatusInfo = promiseHTTP({ uri:statusURL.href, json:true})

**Comment by jvmahon** [comment]
I found a "maybe" fix, but haven't been able to test it as I'm not set up for SSL.
I found a comment on a forum noting a special option that needed to be set in the JavaScript HTTP call to deal with self-certified certificates. 
Can you do an update to 0.0.13 and try your SSL setup again and let me know if it succeeds.

**Comment by meluvalli** [comment]
Didn't work.

It blew up!

<pre>
[12/20/2019, 9:51:07 AM] [HomeSeer] RequestError: Error: write EPROTO 1684:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:
 : Error line 198 - error getting device status info. Check if HomeSeer is running and that JSON interface is enabled, then start homebridge again. Status code: undefined
(node:10804) UnhandledPromiseRejectionWarning: RequestError: Error: write EPROTO 1684:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:

    at new RequestError (C:\HomeBridge\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\HomeBridge\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\HomeBridge\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\HomeBridge\node_modules\homebridge-homeseer4\node_modules\request\request.js:185:22)
    at Request.emit (events.js:305:20)
    at Request.onRequestError (C:\HomeBridge\node_modules\homebridge-homeseer4\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:305:20)
    at TLSSocket.socketErrorListener (_http_client.js:423:9)
    at TLSSocket.emit (events.js:305:20)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
(node:10804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/20/2019, 9:51:07 AM] [HomeSeer] RequestError: Error: write EPROTO 1684:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:
 : Error line 228 - error getting device Control info. Check if HomeSeer is running and that JSON interface is enabled, then start homebridge again. Status code: undefined
</pre>

**Comment by meluvalli** [comment]
Just a reminder, my Cert is a Trusted Cert.  It's from Let's Encrypt Authority X3, so it's trusted by most browsers (Mac, Windows, Linux).  It's not a self signed cert.

**Comment by jvmahon** [comment]
send me an email to my personal account  jvm33@columbia.edu so I can communicate outside this thread.

**Comment by meluvalli** [comment]
Message sent.  Just FYI.

**Comment by meluvalli** [comment]
Issue fixed in 0.0.14!

BIG THANKS TO @jvmahon for all his help!!!!

**Comment by Bi7** [comment]
This issue is back for me with a new upgrade install. I have tried the method in browser, user:password@127.0.01..., to verify and that works fine.
I am using 
homebridge@0.4.50
homebridge-homeseer4@0.0.37
npm@6.13.6
windows-build-tools@5.22

So there are no certs involved (port 80) and the "401 undefined" error happens with or without the No login on same network setting in Homeseer --ver.3.0.0.548 (Windows)

Happy to see this previous conversation but not that the bug is back!

**Comment by jvmahon** [comment]
> This issue is back for me with a new upgrade install. I have tried the method in browser, user:password@127.0.01..., to verify and that works fine.
> I am using
> homebridge@0.4.50
> homebridge-homeseer4@0.0.37
> npm@6.13.6
> windows-build-tools@5.22
> 
> So there are no certs involved (port 80) and the "401 undefined" error happens with or without the No login on same network setting in Homeseer --ver.3.0.0.548 (Windows)
> 
> Happy to see this previous conversation but not that the bug is back!

@Bi7 - I don't quite understand the issue. This issue / thread was about "SSL" support - is that what you are having a problem with?  Are you saying that you had installed 0.0.36 (or earlier) of the homeseer4 plugin and that worked, but it broke in 0.0.37; Or are you saying you had been using the homebridge-homeseer-plugin-2018 and it broke when switching to this plugin?

In either case, please post your entire config.json file (I think you will need to put it into a ".zip" first). Also, please post any error messages that get produced by the plugin so I can see what is going on.
Thanks
Jim

**Comment by Bi7** [comment]
[config.json.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4083785/config.json.zip)

I posted here since I was getting the same error. I have upgraded from homebridge-homeseer-2018 to homebridge-homeseer4. I have not been able to get it working with my config.json. I did verify it with jsonlint.
Here is the error output:

C:\Users\HomeSeerUser\.homebridge>homebridge
[1/18/2020, 10:34:49 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/18/2020, 10:34:49 PM] ---
[1/18/2020, 10:34:53 PM] Loaded plugin: homebridge-homeseer4
homebridge API version: 2.4
[1/18/2020, 10:34:53 PM] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[1/18/2020, 10:34:53 PM] ---
[1/18/2020, 10:34:53 PM] Loading 1 platforms...
[1/18/2020, 10:34:53 PM] [HomeSeer] Initializing HomeSeer platform...
[1/18/2020, 10:34:53 PM] [HomeSeer] Start
Load homebridge-HomeSeerPlatform.HomeSeer
(node:5192) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - undefined
    at new StatusCodeError (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (C:\Users\HomeSeerUser\AppData\Roaming\npm\node_modules\homebridge-homeseer4\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
(node:5192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks for your help!!

**Comment by jvmahon** [comment]
In your config.json, remove 
`````
"batteryRef":0,
`````
from your "SecuritySystem" setup. I'll clarify the wiki instructions on batteries, but if you specify a "batteryRef" it needs to be a non-zero value pointing to the related HomeSeer battery device.

I also found some errors in the networking code -To update, use the command:
`````
npm -g install homebridge-homeseer4
`````
It looks like the code was always using "default", "default" as login and password - I'm not sure if these are the source of your error as the sample file you sent suggested you were using "default", "default" -- but if you are actually using different login / password in your 'real' system, this should fix it. 

This is a debugging build and will include a few extra lines of debugging output in addition to the crash date you got before. If you are still getting a crash, look for the yellow output that begins "*Debug* - status URL:" which is then followed by a http link. Try manually entering that http link at a browser and see if it connects to your homeseer system. 

If you are still getting errors, try the simplified config.json that I've attached to see if that can succeed.

[configSimple.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4085603/configSimple.zip)

IF it is now working, let me know.

**Comment by Bi7** [comment]
Okay,
I have this working now. I was not using default:default. Your fix probably corrected the 401 error.
Thanks.
 I had set up or listed the SecuritySystem ref # in both the simplified and complex section. Having it listed twice caused an error.
Once that was working I received a **status error** which I tracked down to my door lock. The ref # was incorrect as it had recently lost its settings and had to be re-added to the Zwave network. It became a different ref number that I failed to update in my config.json.
Corrected that and it is now working.

HomeKit app set up fine and all is working minus the GarageDoorOpener.

The debug is catching  my virtual device GarageDoorOpener  which has a value of 0, I may open an issue on how to handle that, but still working on it.

Thanks again for the help and your plug-in!

**Comment by jvmahon** [comment]
The "simplified" device entry for the GarageDoorOpener where you enter just the device reference expects it to be either a Z-Wave garage door opener, or the plugin "MyQ or "LiftMaster myQ". For a virtual garage door opener, you will have to detail the parameters used for open, opening, stopped, closing, close. To do this, specify the garage door opener in the "accessories" section. The full set of parameters are listed below. You can get the numeric values from the device's "Status Graphics" page.
See also: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Garage-Door-Openers


`````
{
	"type": "GarageDoorOpener",
	"openValue": 255,     // Control Value used to cause the door to open.
	"closedValue": 0,    // Control Value used to cause the door to close.
	"openingValue": 254,        // Status Value used to indicate the door is opening.
	"closingValue": 252,       // Status Value used to indicate the door is closing
	"stoppedValue": 253       // Status Value used to indicate the door has stopped part-way.
}
`````

**Comment by Bi7** [comment]
Thanks for that. I have add my garage door, contact and sensor controlled to the complex section.
Previously, and now, have only used openValue and closedValue with events written for control.

I will have to re-write the events.

Thanks, and btw, HomeSeer4 seems more responsive, very nice!

**Comment by jvmahon** [comment]
You may not need to rewrite your events if they worked with the "old" plugin as that plugin also had opening / stopped / closing statuses -- you probably just didn't realize that. So if it worked then, it should work now.

**Comment by Bi7** [comment]
I should state this setup is using an Omni panel with one contact sensor and a momentary contact to open/close the garage door. 

"You may not need to rewrite your events..."
Maybe so for opening and closing, but how would Homeseer know for stopped without an event?
There is only the one contact sensor for open or closed. I would think a timer used from state to state (in an event) would be the only way to get that stopped value ( by explicitly setting 253).

I have found the event writing for this difficult because both the action to close/open and the state come from the virtual device. The way I have written my events are to, say for opening, set the virtual device from 0 to 255. 
It just seems that event writing would be much easier if I were to add another sensor to confirm open, rather than just the one I have. In other words, I have no way to confirm the open state except by using a timer (as in "it should be open now!") This has been an okay method but occasionally buggy.
The Homekit app does show opening or closing but that seems to be a separate assumption in the code. 
Would you suggest writing the Event to set the virtual device to openingValue or closingValue to trigger the actions?
