### ISSUE TITLE
Linear GD00Z-4 reports to Homebridge as open when it's closed

### ISSUE THREAD

**Issue by tundrageek-AK** [jvmahon/Homebridge-HomeSeer4#26]
I have a linear GD00Z-4 that's been set up in HomeSeer for a while - I had it working on my older homebridge setup (pre-2018), but when I set it up on this newest plugin, it reports that the door is open. When I right-click the accessory, it reports the correct Current door state of 0, but the next line states that it's target door state is 1. According to the config references, everything seems to be in order - not sure why it's expecting a code of 1.

**Comment by tundrageek-AK** [comment]
![Screenshot 2019-12-28 18 37 59](https://user-images.githubusercontent.com/59325452/71552044-32625500-29a1-11ea-9027-7547b41c3d7d.png)

**Comment by tundrageek-AK** [comment]
{
                    "type": "GarageDoorOpener",
                    "name": "Garage Door Operator",
                    "ref": 29,
                    "uuid_base": "GarageDoor29",
                    "obstructionRef": 26,
                    "obstructionClearValues": [
                        0,
                        70,
                        74
                    ],
                    "openValue": 255,
                    "closedValue": 0,
                    "openingValue": 254,
                    "closingValue": 252,
                    "stoppedValue": 253
                }
![Screenshot 2019-12-28 18 41 27](https://user-images.githubusercontent.com/59325452/71552067-b583ab00-29a1-11ea-80eb-a0044f2ae2c6.png)

**Comment by tundrageek-AK** [comment]
I was just about to close out for the evening and checked the logs one more time to find this gem:
![Screenshot 2019-12-28 18 45 32](https://user-images.githubusercontent.com/59325452/71552096-4a86a400-29a2-11ea-844c-33fdb371a5b2.png)

**Comment by jvmahon** [comment]
No worries. I'm sure  I can get this fixed for you. Can you post an image of the "Status Graphics" page for this device?

Also, try configuring it simply as:

{"type":"GarageDoorOpener", "ref":29}
And let me know what happens.

**Comment by jvmahon** [comment]
Never mind. I think I see the problem and I'm trying to fix it now.

**Comment by tundrageek-AK** [comment]
![Screenshot 2019-12-28 19 11 45](https://user-images.githubusercontent.com/59325452/71552264-ecf45680-29a5-11ea-9b1e-32dfbe3064b1.png)

**Comment by jvmahon** [comment]
I *think* I fixed it, but please test and let me know.
Update to version 0.0.25 by executing
`````
npm -g install homebridge-homeseer4
`````

And try the simplified configuration of:
`````
{"type":"GarageDoorOpener", "ref":29}
`````

One other thing that may be causing a problem - your "Control Use" settings on your Status Graphics page are incorrect.   The  "Control Use" for value 0 should be "Door Lock" and for value 255 should be "Door Unlock"

Thanks.

**Comment by tundrageek-AK** [comment]
Thank you for getting right on this! I have updated the plug-in, simplified the config, and change the Control Use settings, but I'm still getting the same condition - the door is reported as open. The target door state and current door state match up now. Here is what is listed in the log:

[12/28/2019, 11:03:59 PM] [HomeSeer] Host for ASCII Interface set to: 172.16.223.4 at port 11000
[12/28/2019, 11:03:59 PM] Homebridge is running on port 51826.
(node:3331) UnhandledPromiseRejectionWarning: RangeError: Error in GarageDoorOpener - value out of range! Z-Wave Value is: 0
    at Characteristic.CurrentDoorState.<anonymous> (/usr/lib/node_modules/homebridge-homeseer4/lib/HomeKitDeviceSetup.js:490:16)
    at Characteristic.CurrentDoorState.emit (events.js:210:5)
    at updateAllFromHSData (/usr/lib/node_modules/homebridge-homeseer4/index.js:516:18)
    at /usr/lib/node_modules/homebridge-homeseer4/index.js:361:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvmahon** [comment]
Update to 0.0.26 and try again and let me know if its all working now.
Thanks.

To update . . .
`````
npm -g install homebridge-homeseer4
`````

**Comment by tundrageek-AK** [comment]
That fixed it. THANK YOU!!
